#pragma once

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(ESP_FRAME_EVENT);

enum {
    EVENT_SEND_NETWORK,
    EVENT_SEND_CLIENT_INFO,

    DATA_FRAME_EVENT_EAPOLKEY_FRAME,
    DATA_FRAME_EVENT_PMKID,

    BLE_SCANNER_DEVICE_FOUND
};